export const ZONAS_CALIDAD = [
  "Recibo",
  "Empaque",
  "Logística",
  "Cocina Preliminar",
  "Cocina Postres",
  "Heladería",
  "Economato",
  "Cocinas Hornos 1",
  "Cocina Panadería",
  "Cocina Salsas",
  "Cocina Panetti",
  "Cocina Wajaca",
  "Cocina Caliente",
  "Aseo 1",
  "Pasillos Piso 1",
  "Oficinas",
  "Cafetín",
  "Cocinas Hornos 2",
  "Cocina Tombler",
  "Cocina Cerdo",
  "Cocina Res",
  "Cocina Pollo",
  "Cocina Empaque",
  "Pasillos Piso 2",
  "Aseo 2",
] as const;

export type ZonaCalidad = (typeof ZONAS_CALIDAD)[number];
