// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecepcionMP.Infrastructure.Persistence;

#nullable disable

namespace RecepcionMP.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CheckListBPM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("ObservacionesGenerales")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecepcionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecepcionId")
                        .IsUnique();

                    b.ToTable("CheckListsBPM");
                });

            modelBuilder.Entity("CheckListItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CheckListBPMId")
                        .HasColumnType("int");

                    b.Property<bool>("EsConforme")
                        .HasColumnType("bit");

                    b.Property<bool>("EsCritico")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CheckListBPMId");

                    b.ToTable("CheckListItem");
                });

            modelBuilder.Entity("Lote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CantidadRecibida")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FechaFabricacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<bool>("LiberadoCalidad")
                        .HasColumnType("bit");

                    b.Property<string>("NumeroLote")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecepcionId")
                        .HasColumnType("int");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("RecepcionId");

                    b.ToTable("Lotes");
                });

            modelBuilder.Entity("Recepcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActualizadoPor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int?>("FacturaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaHoraTemperatura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRecepcion")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotivoCambioEstado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreTransportista")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrdenCompraId")
                        .HasColumnType("int");

                    b.Property<string>("PlacaVehiculo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProveedorId")
                        .HasColumnType("int");

                    b.Property<bool>("RequiereAprobacionCalidad")
                        .HasColumnType("bit");

                    b.Property<decimal?>("TemperaturaAlAbrirPuertas")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FacturaId");

                    b.HasIndex("OrdenCompraId");

                    b.HasIndex("ProveedorId");

                    b.ToTable("Recepciones");
                });

            modelBuilder.Entity("RecepcionMP.Domain.Entities.AccionCorrectiva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CerradaPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreadaPor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaCompletacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaUltimaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("NoConformidadId")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Responsable")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("FechaVencimiento");

                    b.HasIndex("Responsable");

                    b.HasIndex("NoConformidadId", "Estado");

                    b.ToTable("AccionesCorrectivas");
                });

            modelBuilder.Entity("RecepcionMP.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoAlimento")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("RecepcionMP.Domain.Entities.CheckListBPMCategoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("CriteriosJSON")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsVigente")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaVigencia")
                        .HasColumnType("datetime2");

                    b.Property<int>("Versión")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("CheckListsBPMCategorias");
                });

            modelBuilder.Entity("RecepcionMP.Domain.Entities.DocumentoAdjunto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CargadoPor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescargadoPor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaDescarga")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("HashSHA256")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IntegridadVerificada")
                        .HasColumnType("bit");

                    b.Property<string>("MotivoEliminacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreArchivoAlmacenado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreArchivoOriginal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PendienteEliminacion")
                        .HasColumnType("bit");

                    b.Property<int>("RecepcionDocumentoId")
                        .HasColumnType("int");

                    b.Property<string>("RutaCompleta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TamañoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoMime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HashSHA256")
                        .IsUnique();

                    b.HasIndex("RecepcionDocumentoId");

                    b.HasIndex("PendienteEliminacion", "FechaEliminacion");

                    b.ToTable("DocumentosAdjuntos");
                });

            modelBuilder.Entity("RecepcionMP.Domain.Entities.DocumentoProveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVigencia")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("int");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProveedorId");

                    b.ToTable("DocumentoProveedor");
                });

            modelBuilder.Entity("RecepcionMP.Domain.Entities.DocumentoRequerido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsObligatorio")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaVigencia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoDocumento")
                        .HasColumnType("int");

                    b.Property<int>("Versión")
                        .HasColumnType("int");

                    b.Property<int?>("VigenciaDias")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("DocumentosRequeridos");
                });

            modelBuilder.Entity("RecepcionMP.Domain.Entities.DocumentoValidacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DocumentoRequeridoId")
                        .HasColumnType("int");

                    b.Property<bool>("EsValido")
                        .HasColumnType("bit");

                    b.Property<bool>("EstaVigente")
                        .HasColumnType("bit");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaValidacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVencimientoDocumento")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotivoRechazo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecepcionDocumentoId")
                        .HasColumnType("int");

                    b.Property<string>("ResultadoValidacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValidadoPor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoRequeridoId");

                    b.HasIndex("FechaValidacion");

                    b.HasIndex("RecepcionDocumentoId", "Estado");

                    b.ToTable("DocumentosValidacion");
                });

            modelBuilder.Entity("RecepcionMP.Domain.Entities.Factura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrdenCompraId")
                        .HasColumnType("int");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrdenCompraId");

                    b.ToTable("Factura");
                });

            modelBuilder.Entity("RecepcionMP.Domain.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("CategoriaSanitaria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProveedorId")
                        .HasColumnType("int");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TemperaturaMaxima")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TemperaturaMinima")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TemperaturaObjetivo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VidaUtilDias")
                        .HasColumnType("int");

                    b.Property<int>("VidaUtilMinimaAceptable")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ProveedorId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("RecepcionMP.Domain.Entities.LiberacionLote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaDecision")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaUltimaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("LiberadoPor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoteId")
                        .HasColumnType("int");

                    b.Property<int?>("LoteId1")
                        .HasColumnType("int");

                    b.Property<string>("MotivoRechazo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecepcionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaDecision");

                    b.HasIndex("LoteId");

                    b.HasIndex("LoteId1")
                        .IsUnique()
                        .HasFilter("[LoteId1] IS NOT NULL");

                    b.HasIndex("RecepcionId");

                    b.ToTable("LiberacionesLotes");
                });

            modelBuilder.Entity("RecepcionMP.Domain.Entities.NoConformidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CantidadAfectada")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Causa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaUltimaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("LoteId")
                        .HasColumnType("int");

                    b.Property<int?>("LoteId1")
                        .HasColumnType("int");

                    b.Property<int>("RecepcionId")
                        .HasColumnType("int");

                    b.Property<string>("RegistradoPor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FechaRegistro");

                    b.HasIndex("LoteId");

                    b.HasIndex("LoteId1");

                    b.HasIndex("RecepcionId", "Estado");

                    b.ToTable("NoConformidades");
                });

            modelBuilder.Entity("RecepcionMP.Domain.Entities.OrdenCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaOrden")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroOrden")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProveedorId");

                    b.ToTable("OrdenesCompra");
                });

            modelBuilder.Entity("RecepcionMP.Domain.Entities.OrdenCompraItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CantidadEsperada")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrdenCompraId")
                        .HasColumnType("int");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("OrdenCompraId");

                    b.ToTable("OrdenCompraItem");
                });

            modelBuilder.Entity("RecepcionMP.Domain.Entities.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Contacto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NIT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("RecepcionMP.Domain.Entities.RecepcionDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CargadoPor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DocumentoRequeridoId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("datetime2");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObservacionesValidacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecepcionId")
                        .HasColumnType("int");

                    b.Property<string>("RutaAlmacenamiento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TamañoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoMime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoRequeridoId");

                    b.HasIndex("RecepcionId", "DocumentoRequeridoId")
                        .IsUnique();

                    b.ToTable("RecepcionesDocumentos");
                });

            modelBuilder.Entity("RecepcionMP.Domain.Entities.RegistroAuditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Accion")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("IP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotivoRechazo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegistroId")
                        .HasColumnType("int");

                    b.Property<string>("Tabla")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ValoresAntes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValoresDespues")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("Tabla", "RegistroId", "FechaHora");

                    b.ToTable("RegistrosAuditoria");
                });

            modelBuilder.Entity("CheckListBPM", b =>
                {
                    b.HasOne("Recepcion", "Recepcion")
                        .WithOne("CheckListBPM")
                        .HasForeignKey("CheckListBPM", "RecepcionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recepcion");
                });

            modelBuilder.Entity("CheckListItem", b =>
                {
                    b.HasOne("CheckListBPM", "CheckListBPM")
                        .WithMany("Items")
                        .HasForeignKey("CheckListBPMId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CheckListBPM");
                });

            modelBuilder.Entity("Lote", b =>
                {
                    b.HasOne("RecepcionMP.Domain.Entities.Item", "Item")
                        .WithMany("Lotes")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recepcion", "Recepcion")
                        .WithMany("Lotes")
                        .HasForeignKey("RecepcionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Recepcion");
                });

            modelBuilder.Entity("Recepcion", b =>
                {
                    b.HasOne("RecepcionMP.Domain.Entities.Factura", "Factura")
                        .WithMany("Recepciones")
                        .HasForeignKey("FacturaId");

                    b.HasOne("RecepcionMP.Domain.Entities.OrdenCompra", "OrdenCompra")
                        .WithMany()
                        .HasForeignKey("OrdenCompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecepcionMP.Domain.Entities.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorId");

                    b.Navigation("Factura");

                    b.Navigation("OrdenCompra");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("RecepcionMP.Domain.Entities.AccionCorrectiva", b =>
                {
                    b.HasOne("RecepcionMP.Domain.Entities.NoConformidad", "NoConformidad")
                        .WithMany("AccionesCorrectivas")
                        .HasForeignKey("NoConformidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NoConformidad");
                });

            modelBuilder.Entity("RecepcionMP.Domain.Entities.CheckListBPMCategoria", b =>
                {
                    b.HasOne("RecepcionMP.Domain.Entities.Categoria", "Categoria")
                        .WithMany("CheckListsVersionados")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("RecepcionMP.Domain.Entities.DocumentoAdjunto", b =>
                {
                    b.HasOne("RecepcionMP.Domain.Entities.RecepcionDocumento", "RecepcionDocumento")
                        .WithMany()
                        .HasForeignKey("RecepcionDocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecepcionDocumento");
                });

            modelBuilder.Entity("RecepcionMP.Domain.Entities.DocumentoProveedor", b =>
                {
                    b.HasOne("RecepcionMP.Domain.Entities.Proveedor", "Proveedor")
                        .WithMany("Documentos")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("RecepcionMP.Domain.Entities.DocumentoRequerido", b =>
                {
                    b.HasOne("RecepcionMP.Domain.Entities.Categoria", "Categoria")
                        .WithMany("DocumentosRequeridos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("RecepcionMP.Domain.Entities.DocumentoValidacion", b =>
                {
                    b.HasOne("RecepcionMP.Domain.Entities.DocumentoRequerido", "DocumentoRequerido")
                        .WithMany()
                        .HasForeignKey("DocumentoRequeridoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecepcionMP.Domain.Entities.RecepcionDocumento", "RecepcionDocumento")
                        .WithMany()
                        .HasForeignKey("RecepcionDocumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DocumentoRequerido");

                    b.Navigation("RecepcionDocumento");
                });

            modelBuilder.Entity("RecepcionMP.Domain.Entities.Factura", b =>
                {
                    b.HasOne("RecepcionMP.Domain.Entities.OrdenCompra", "OrdenCompra")
                        .WithMany()
                        .HasForeignKey("OrdenCompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdenCompra");
                });

            modelBuilder.Entity("RecepcionMP.Domain.Entities.Item", b =>
                {
                    b.HasOne("RecepcionMP.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Items")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecepcionMP.Domain.Entities.Proveedor", null)
                        .WithMany("Items")
                        .HasForeignKey("ProveedorId");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("RecepcionMP.Domain.Entities.LiberacionLote", b =>
                {
                    b.HasOne("Lote", "Lote")
                        .WithMany()
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Lote", null)
                        .WithOne("Liberacion")
                        .HasForeignKey("RecepcionMP.Domain.Entities.LiberacionLote", "LoteId1");

                    b.HasOne("Recepcion", "Recepcion")
                        .WithMany()
                        .HasForeignKey("RecepcionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Lote");

                    b.Navigation("Recepcion");
                });

            modelBuilder.Entity("RecepcionMP.Domain.Entities.NoConformidad", b =>
                {
                    b.HasOne("Lote", "Lote")
                        .WithMany()
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Lote", null)
                        .WithMany("NoConformidades")
                        .HasForeignKey("LoteId1");

                    b.HasOne("Recepcion", "Recepcion")
                        .WithMany()
                        .HasForeignKey("RecepcionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Lote");

                    b.Navigation("Recepcion");
                });

            modelBuilder.Entity("RecepcionMP.Domain.Entities.OrdenCompra", b =>
                {
                    b.HasOne("RecepcionMP.Domain.Entities.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("RecepcionMP.Domain.Entities.OrdenCompraItem", b =>
                {
                    b.HasOne("RecepcionMP.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecepcionMP.Domain.Entities.OrdenCompra", "OrdenCompra")
                        .WithMany("Items")
                        .HasForeignKey("OrdenCompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("OrdenCompra");
                });

            modelBuilder.Entity("RecepcionMP.Domain.Entities.RecepcionDocumento", b =>
                {
                    b.HasOne("RecepcionMP.Domain.Entities.DocumentoRequerido", "DocumentoRequerido")
                        .WithMany("RecepcionesDocumentos")
                        .HasForeignKey("DocumentoRequeridoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recepcion", "Recepcion")
                        .WithMany("Documentos")
                        .HasForeignKey("RecepcionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentoRequerido");

                    b.Navigation("Recepcion");
                });

            modelBuilder.Entity("CheckListBPM", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Lote", b =>
                {
                    b.Navigation("Liberacion");

                    b.Navigation("NoConformidades");
                });

            modelBuilder.Entity("Recepcion", b =>
                {
                    b.Navigation("CheckListBPM");

                    b.Navigation("Documentos");

                    b.Navigation("Lotes");
                });

            modelBuilder.Entity("RecepcionMP.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("CheckListsVersionados");

                    b.Navigation("DocumentosRequeridos");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("RecepcionMP.Domain.Entities.DocumentoRequerido", b =>
                {
                    b.Navigation("RecepcionesDocumentos");
                });

            modelBuilder.Entity("RecepcionMP.Domain.Entities.Factura", b =>
                {
                    b.Navigation("Recepciones");
                });

            modelBuilder.Entity("RecepcionMP.Domain.Entities.Item", b =>
                {
                    b.Navigation("Lotes");
                });

            modelBuilder.Entity("RecepcionMP.Domain.Entities.NoConformidad", b =>
                {
                    b.Navigation("AccionesCorrectivas");
                });

            modelBuilder.Entity("RecepcionMP.Domain.Entities.OrdenCompra", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("RecepcionMP.Domain.Entities.Proveedor", b =>
                {
                    b.Navigation("Documentos");

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
