import {
  type NoConformidad, EstadoNC, TipoNC, PrioridadNC,
} from "../../Services/no-conformidades.service";

export const MOCK_NC: NoConformidad[] = [
  {
    id: "nc-001",
    numero: "NC-2026-0001",
    titulo: "Temperatura fuera de rango en lote de pollo",
    tipo: TipoNC.TemperaturaFueraRango,
    prioridad: PrioridadNC.Alta,
    estado: EstadoNC.Abierta,
    descripcion: "La temperatura registrada al ingreso fue 5.9°C, fuera del rango permitido (0-4°C).",
    causalNombre: "Temperatura fuera de rango",
    proveedorNombre: "AviCol S.A.",
    numeroLote: "L-2026-0048-01",
    itemNombre: "Pechuga de pollo",
    cantidadAfectada: 50,
    asignadoA: "Calidad",
    fechaLimite: "2026-03-05",
    // causaRaiz y observacionesCierre no se incluyen (undefined)
    creadoEn: "2026-02-24T08:00:00Z",
    creadoPorNombre: "Juan Pérez",
    totalAcciones: 1,
    accionesPendientes: 1,
    accionesCorrectivas: [
      {
        id: "ac-001",
        descripcion: "Realizar análisis microbiológico del lote en cuarentena.",
        responsable: "Laboratorio",
        fechaCompromiso: "2026-02-27",
        estado: "Pendiente",
      },
    ],
    comentarios: [],
  },
  {
    id: "nc-002",
    numero: "NC-2026-0017",
    tipo: TipoNC.DocumentacionIncompleta,
    prioridad: PrioridadNC.Media,
    estado: EstadoNC.EnProceso,
    titulo: "COA no presentado en recepción — azúcar morena",
    descripcion: "El proveedor Riopaila Castilla no presentó el Certificado de Análisis (COA) del lote de azúcar morena al momento de la recepción.",
    causalNombre: "Documentación incompleta",
    proveedorNombre: "Riopaila Castilla",
    numeroLote: "L-2026-0044-02",
    itemNombre: "Azúcar morena",
    asignadoA: "Patricia Silva",
    fechaLimite: "2026-02-28",
    creadoEn: "2026-02-21T11:00:00Z",
    creadoPorNombre: "Andrés Torres",
    totalAcciones: 1,
    accionesPendientes: 0,
    accionesCorrectivas: [
      {
        id: "ac-004",
        descripcion: "Solicitar COA a Riopaila Castilla vía correo con plazo de 48 horas.",
        responsable: "Patricia Silva",
        fechaCompromiso: "2026-02-23",
        estado: "Completada",
        fechaCierre: "2026-02-22T10:00:00Z",
        evidencia: "COA recibido y archivado en sistema.",
      },
    ],
    comentarios: [],
  },
  {
    id: "nc-003",
    numero: "NC-2026-0016",
    tipo: TipoNC.Merma,
    prioridad: PrioridadNC.Baja,
    estado: EstadoNC.Abierta,
    titulo: "Diferencia de 2 kg en cantidad recibida vs OC — azúcar refinada",
    descripcion: "Se recibieron 1,998 Kg de azúcar refinada contra los 2,000 Kg de la OC. Diferencia de 2 Kg (0.1%).",
    causalNombre: "Cantidad incorrecta",
    proveedorNombre: "Riopaila Castilla",
    numeroLote: "L-2026-0044-01",
    itemNombre: "Azúcar refinada",
    cantidadAfectada: 2,
    creadoEn: "2026-02-21T11:30:00Z",
    creadoPorNombre: "Andrés Torres",
    totalAcciones: 0,
    accionesPendientes: 0,
    accionesCorrectivas: [],
    comentarios: [],
  },
  {
    id: "nc-004",
    numero: "NC-2026-0015",
    tipo: TipoNC.RotuladoNoConforme,
    prioridad: PrioridadNC.Critica,
    estado: EstadoNC.Cerrada,
    titulo: "Etiqueta sin fecha de vencimiento visible — yogur natural",
    descripcion: "La etiqueta del yogur natural presentaba fecha de vencimiento ilegible por impresión defectuosa. Incumple Res. 5109/2005.",
    causalNombre: "Rotulado no conforme",
    proveedorNombre: "Lácteos del Valle",
    itemNombre: "Yogur natural",
    asignadoA: "Laura Gómez",
    fechaLimite: "2026-02-24",
    fechaCierre: "2026-02-24T08:00:00Z",
    causaRaiz: "Falla en impresora de fechas del proveedor. Lote reemplazado con rotulado correcto.",
    creadoEn: "2026-02-23T08:30:00Z",
    creadoPorNombre: "Laura Gómez",
    totalAcciones: 1,
    accionesPendientes: 0,
    accionesCorrectivas: [
      {
        id: "ac-005",
        descripcion: "Rechazar lote y solicitar reposición inmediata con rotulado conforme.",
        responsable: "Laura Gómez",
        fechaCompromiso: "2026-02-24",
        estado: "Completada",
        fechaCierre: "2026-02-24T07:00:00Z",
        evidencia: "Lote repuesto. Acta de reposición firmada y archivada.",
      },
    ],
    comentarios: [],
  },
  {
    id: "nc-005",
    numero: "NC-2026-0014",
    tipo: TipoNC.CalidadSensorial,
    prioridad: PrioridadNC.Alta,
    estado: EstadoNC.Cerrada,
    titulo: "Olor atípico en queso doble crema — rechazo total",
    descripcion: "Queso doble crema presentó olor ligeramente ácido-rancio durante inspección sensorial. Lote rechazado en recepción.",
    causalNombre: "Calidad sensorial no conforme",
    proveedorNombre: "Lácteos del Valle",
    itemNombre: "Queso doble crema",
    cantidadAfectada: 50,
    fechaCierre: "2026-02-23T12:00:00Z",
    causaRaiz: "Ruptura de cadena de frío en almacenamiento del proveedor previo al despacho.",
    creadoEn: "2026-02-23T09:15:00Z",
    creadoPorNombre: "Laura Gómez",
    totalAcciones: 1,
    accionesPendientes: 0,
    accionesCorrectivas: [
      {
        id: "ac-006",
        descripcion: "Rechazo total del lote y devolución al proveedor con acta.",
        responsable: "Laura Gómez",
        fechaCompromiso: "2026-02-23",
        estado: "Completada",
        fechaCierre: "2026-02-23T12:00:00Z",
        evidencia: "Acta de devolución No. DEV-2026-0023 firmada.",
      },
    ],
    comentarios: [],
  },
];