import type { components } from './api'

// Commands y tipos relacionados a comandos (requests para la API)

export type ActualizarCheckListCommand = components['schemas']['ActualizarCheckListCommand']
export type ActualizarCriteriosCommand = components['schemas']['ActualizarCriteriosCommand']
export type ActualizarEstadoOCCommand = components['schemas']['ActualizarEstadoOCCommand']
export type ActualizarItemCommand = components['schemas']['ActualizarItemCommand']
export type ActualizarOCCommand = components['schemas']['ActualizarOCCommand']
export type ActualizarProveedorCommand = components['schemas']['ActualizarProveedorCommand']
export type AgregarComentarioNCCommand = components['schemas']['AgregarComentarioNCCommand']
export type AgregarItemRecepcionCommand = components['schemas']['AgregarItemRecepcionCommand']
export type CerrarNCDirectoCommand = components['schemas']['CerrarNCDirectoCommand']
export type CerrarNoConformidadCommand = components['schemas']['CerrarNoConformidadCommand']
export type CrearAccionCorrectivaCommand = components['schemas']['CrearAccionCorrectivaCommand']
export type CrearChecklistCommand = components['schemas']['CrearChecklistCommand']
export type CrearItemCommand = components['schemas']['CrearItemCommand']
export type CrearNoConformidadCommand = components['schemas']['CrearNoConformidadCommand']
export type CrearOrdenCompraCommand = components['schemas']['CrearOrdenCompraCommand']
export type CrearProveedorCommand = components['schemas']['CrearProveedorCommand']
export type CriterioRequest = components['schemas']['CriterioRequest']
export type DecisionLiberacion = components['schemas']['DecisionLiberacion']
export type DetalleOrdenCompraRequest = components['schemas']['DetalleOrdenCompraRequest']
export type EstadoNoConformidad = components['schemas']['EstadoNoConformidad']
export type EstadoOrdenCompra = components['schemas']['EstadoOrdenCompra']
export type EstadoProveedor = components['schemas']['EstadoProveedor']
export type EstadoRecepcion = components['schemas']['EstadoRecepcion']
export type IniciarRecepcionCommand = components['schemas']['IniciarRecepcionCommand']
export type ItemChecklistRequest = components['schemas']['ItemChecklistRequest']
export type LiberarLoteCommand = components['schemas']['LiberarLoteCommand']
export type OrigenTemperatura = components['schemas']['OrigenTemperatura']
export type PonerEnCuarentenaCommand = components['schemas']['PonerEnCuarentenaCommand']
export type PrioridadNoConformidad = components['schemas']['PrioridadNoConformidad']
export type ProblemDetails = components['schemas']['ProblemDetails']
export type RechazarLoteCommand = components['schemas']['RechazarLoteCommand']
export type RegistrarInspeccionVehiculoCommand = components['schemas']['RegistrarInspeccionVehiculoCommand']
export type RegistrarResultadoChecklistCommand = components['schemas']['RegistrarResultadoChecklistCommand']
export type RegistrarTemperaturaCommand = components['schemas']['RegistrarTemperaturaCommand']
export type ResultadoItem = components['schemas']['ResultadoItem']
export type ResultadoItemRequest = components['schemas']['ResultadoItemRequest']
export type TipoCriterio = components['schemas']['TipoCriterio']
export type TipoDocumento = components['schemas']['TipoDocumento']
export type TipoNoConformidad = components['schemas']['TipoNoConformidad']
export type RegistrarLotesCommand = components['schemas']['RegistrarLotesCommand']
export type ItemConLotesDto = components['schemas']['ItemConLotesDto']
export type DetalleLoteDto = components['schemas']['DetalleLoteDto']