import type { RecepcionResumen, RecepcionDetalle } from "../../Services/recepciones.service";
import { EstadoRecepcion, TipoDocumento, OrigenTemperatura, EstadoSensorial, EstadoRotulado, UbicacionDestino } from "../../Types/api";

// ─── LISTADO ──────────────────────────────────────────────────────────────────

export const MOCK_RECEPCIONES: RecepcionResumen[] = [
  {
    id: "rec-001", numeroRecepcion: "REC-2026-0048",
    ordenCompraNumero: "OC-2026-0112", proveedorNombre: "AviCol S.A.", proveedorId: "prov-001",
    fechaRecepcion: "2026-02-24", horaLlegadaVehiculo: "07:30:00",
    placaVehiculo: "OPQ-451", nombreTransportista: "Luis García",
    estado: EstadoRecepcion.PendienteCalidad,
    totalLotes: 3, lotesLiberados: 0, lotesRechazados: 0,
  },
  {
    id: "rec-002", numeroRecepcion: "REC-2026-0047",
    ordenCompraNumero: "OC-2026-0109", proveedorNombre: "Lácteos del Valle", proveedorId: "prov-002",
    fechaRecepcion: "2026-02-23", horaLlegadaVehiculo: "08:15:00",
    placaVehiculo: "JKL-782", nombreTransportista: "Carlos Rueda",
    estado: EstadoRecepcion.Liberada,
    totalLotes: 5, lotesLiberados: 5, lotesRechazados: 0,
  },
  {
    id: "rec-003", numeroRecepcion: "REC-2026-0046",
    ordenCompraNumero: "OC-2026-0105", proveedorNombre: "Riopaila Castilla", proveedorId: "prov-003",
    fechaRecepcion: "2026-02-23", horaLlegadaVehiculo: "10:00:00",
    placaVehiculo: "ABC-123",
    estado: EstadoRecepcion.Rechazada,
    totalLotes: 2, lotesLiberados: 1, lotesRechazados: 1,
  },
  {
    id: "rec-004", numeroRecepcion: "REC-2026-0045",
    ordenCompraNumero: "OC-2026-0101", proveedorNombre: "Frigorífico Guadalupe", proveedorId: "prov-004",
    fechaRecepcion: "2026-02-22", horaLlegadaVehiculo: "06:45:00",
    placaVehiculo: "DEF-999", nombreTransportista: "Mario Pérez",
    estado: EstadoRecepcion.Liberada,
    totalLotes: 4, lotesLiberados: 3, lotesRechazados: 1,
  },
  {
    id: "rec-005", numeroRecepcion: "REC-2026-0044",
    ordenCompraNumero: "OC-2026-0098", proveedorNombre: "Harinas del Meta S.A.", proveedorId: "prov-005",
    fechaRecepcion: "2026-02-21", horaLlegadaVehiculo: "09:30:00",
    estado: EstadoRecepcion.RegistroLotes,
    totalLotes: 2, lotesLiberados: 0, lotesRechazados: 0,
  },
  {
    id: "rec-006", numeroRecepcion: "REC-2026-0043",
    ordenCompraNumero: "OC-2026-0094", proveedorNombre: "Alimentos Deli Ltda.", proveedorId: "prov-006",
    fechaRecepcion: "2026-02-20", horaLlegadaVehiculo: "11:00:00",
    placaVehiculo: "GHI-555",
    estado: EstadoRecepcion.InspeccionVehiculo,
    totalLotes: 0, lotesLiberados: 0, lotesRechazados: 0,
  },
];

// ─── DETALLE (para DetalleRecepcionPage) ─────────────────────────────────────

export const MOCK_DETALLE: RecepcionDetalle = {
  // campos heredados de RecepcionResumen
  id:                    "rec-001",
  numeroRecepcion:       "REC-2026-0048",
  ordenCompraNumero:     "OC-2026-0112",
  ordenCompraId:         "oc-112",
  proveedorNombre:       "AviCol S.A.",
  proveedorId:           "prov-001",
  fechaRecepcion:        "2026-02-24",
  horaLlegadaVehiculo:   "07:30:00",
  placaVehiculo:         "OPQ-451",
  nombreTransportista:   "Luis García",
  estado:                EstadoRecepcion.PendienteCalidad,
  totalLotes:            3,
  lotesLiberados:        0,
  lotesRechazados:       0,
  observacionesGenerales: "Vehículo llegó puntual. Sin novedades en el ingreso.",

  // inspección vehículo
  inspeccionVehiculo: {
    temperaturaInicial:      4.2,
    temperaturaDentroRango:  true,
    integridadEmpaque:       true,
    limpiezaVehiculo:        true,
    presenciaOloresExtranos: false,
    plagasVisible:           false,
    documentosTransporteOk:  true,
    observaciones:           "Compartimento limpio y con temperatura adecuada.",
    fechaRegistro:           "2026-02-24T07:35:00Z",
  },

  // lotes recibidos
  lotes: [
    {
      id:                   "lote-001",
      itemId:               "item-pollo",
      itemNombre:           "Pollo entero fresco",
      itemCodigo:           "AVE-001",
      detalleOcId:          "det-001",
      numeroLoteProveedor:  "AVI-20260224-A",
      numeroLoteInterno:    "LI-2026-0301",
      fechaFabricacion:     "2026-02-23",
      fechaVencimiento:     "2026-03-01",
      cantidadRecibida:     120,
      cantidadEsperada:     120,
      unidadMedida:         "Kg",
      temperaturaMedida:    3.8,
      estadoSensorial:      EstadoSensorial.Aceptable,
      estadoRotulado:       EstadoRotulado.Conforme,
      ubicacionDestino:     UbicacionDestino.Almacen,
      estado:               "PendienteCalidad",
      documentos: [
        {
          id:            "doc-lote-001",
          tipoDocumento: TipoDocumento.CertificadoAnalisis,
          nombreArchivo: "COA_AVI_20260224.pdf",
          urlDescarga:   "#",
          fechaCarga:    "2026-02-24T07:40:00Z",
        },
      ],
    },
    {
      id:                   "lote-002",
      itemId:               "item-muslo",
      itemNombre:           "Muslo de pollo",
      itemCodigo:           "AVE-002",
      detalleOcId:          "det-002",
      numeroLoteProveedor:  "AVI-20260224-B",
      numeroLoteInterno:    "LI-2026-0302",
      fechaFabricacion:     "2026-02-23",
      fechaVencimiento:     "2026-03-02",
      cantidadRecibida:     80,
      cantidadEsperada:     100,
      unidadMedida:         "Kg",
      temperaturaMedida:    4.1,
      estadoSensorial:      EstadoSensorial.Aceptable,
      estadoRotulado:       EstadoRotulado.Conforme,
      ubicacionDestino:     UbicacionDestino.Almacen,
      estado:               "PendienteCalidad",
      documentos:           [],
    },
    {
      id:                   "lote-003",
      itemId:               "item-pechuga",
      itemNombre:           "Pechuga de pollo sin hueso",
      itemCodigo:           "AVE-003",
      detalleOcId:          "det-003",
      numeroLoteProveedor:  "AVI-20260224-C",
      numeroLoteInterno:    "LI-2026-0303",
      fechaFabricacion:     "2026-02-24",
      fechaVencimiento:     "2026-03-03",
      cantidadRecibida:     50,
      cantidadEsperada:     50,
      unidadMedida:         "Kg",
      temperaturaMedida:    5.9,
      estadoSensorial:      EstadoSensorial.Dudoso,
      estadoRotulado:       EstadoRotulado.Conforme,
      ubicacionDestino:     UbicacionDestino.Cuarentena,
      estado:               "PendienteCalidad",
      documentos:           [],
    },
  ],

  // documentos de la recepción
  documentos: [
    {
      id:            "doc-rec-001",
      tipoDocumento: TipoDocumento.RegistroSanitarioINVIMA,
      nombreArchivo: "INVIMA_AviCol_2026.pdf",
      urlDescarga:   "#",
      fechaCarga:    "2026-02-24T07:38:00Z",
    },
    {
      id:            "doc-rec-002",
      tipoDocumento: TipoDocumento.CertificadoTransporte,
      nombreArchivo: "BitacoraTemp_OPQ451_20260224.pdf",
      urlDescarga:   "#",
      fechaCarga:    "2026-02-24T07:39:00Z",
    },
  ],

  // registros de temperatura
  temperaturas: [
    {
      id:               "temp-001",
      temperatura:      3.8,
      unidadMedida:     "°C",
      fechaRegistro:    "2026-02-24T07:31:00Z",
      origen:           OrigenTemperatura.Manual,
      estaFueraDeRango: false,
      loteId:           "lote-001",
      loteNumero:       "LI-2026-0301",
      itemNombre:       "Pollo entero fresco",
    },
    {
      id:               "temp-002",
      temperatura:      4.1,
      unidadMedida:     "°C",
      fechaRegistro:    "2026-02-24T07:32:00Z",
      origen:           OrigenTemperatura.Bluetooth,
      estaFueraDeRango: false,
      loteId:           "lote-002",
      loteNumero:       "LI-2026-0302",
      itemNombre:       "Muslo de pollo",
    },
    {
      id:               "temp-003",
      temperatura:      5.9,
      unidadMedida:     "°C",
      fechaRegistro:    "2026-02-24T07:33:00Z",
      origen:           OrigenTemperatura.Manual,
      estaFueraDeRango: true,
      observacion:      "Temperatura ligeramente elevada — lote enviado a cuarentena.",
      loteId:           "lote-003",
      loteNumero:       "LI-2026-0303",
      itemNombre:       "Pechuga de pollo sin hueso",
    },
  ],
};