import type { RecepcionResumen, RecepcionDetalle } from "../../Services/recepciones.service";
import { EstadoRecepcion, OrigenTemperatura } from "../../Types/api";

export const MOCK_RECEPCIONES: RecepcionResumen[] = [
  {
    id: "rec-001", numeroRecepcion: "REC-2026-0048",
    ordenCompraNumero: "OC-2026-0112",
    proveedorNombre: "AviCol S.A.", proveedorId: "prov-001",
    fechaRecepcion: "2026-02-24", horaLlegadaVehiculo: "07:30:00",
    placaVehiculo: "OPQ-451", nombreTransportista: "Luis García",
    estado: EstadoRecepcion.PendienteCalidad,
    totalLotes: 3, lotesLiberados: 0, lotesRechazados: 0,
  },
  {
    id: "rec-002", numeroRecepcion: "REC-2026-0047",
    ordenCompraNumero: "OC-2026-0109",
    proveedorNombre: "Lácteos del Valle", proveedorId: "prov-002",
    fechaRecepcion: "2026-02-23", horaLlegadaVehiculo: "08:15:00",
    placaVehiculo: "JKL-782", nombreTransportista: "Carlos Rueda",
    estado: EstadoRecepcion.Liberada,
    totalLotes: 5, lotesLiberados: 5, lotesRechazados: 0,
  },
  {
    id: "rec-003", numeroRecepcion: "REC-2026-0046",
    ordenCompraNumero: "OC-2026-0105",
    proveedorNombre: "Riopaila Castilla", proveedorId: "prov-003",
    fechaRecepcion: "2026-02-23", horaLlegadaVehiculo: "10:00:00",
    placaVehiculo: "ABC-123",
    estado: EstadoRecepcion.Rechazada,
    totalLotes: 2, lotesLiberados: 1, lotesRechazados: 1,
  },
  {
    id: "rec-004", numeroRecepcion: "REC-2026-0045",
    ordenCompraNumero: "OC-2026-0101",
    proveedorNombre: "Frigorífico Guadalupe", proveedorId: "prov-004",
    fechaRecepcion: "2026-02-22", horaLlegadaVehiculo: "06:45:00",
    placaVehiculo: "DEF-999", nombreTransportista: "Mario Pérez",
    estado: EstadoRecepcion.Liberada,
    totalLotes: 4, lotesLiberados: 3, lotesRechazados: 1,
  },
  {
    id: "rec-005", numeroRecepcion: "REC-2026-0044",
    ordenCompraNumero: "OC-2026-0098",
    proveedorNombre: "Harinas del Meta S.A.", proveedorId: "prov-005",
    fechaRecepcion: "2026-02-21", horaLlegadaVehiculo: "09:30:00",
    estado: EstadoRecepcion.RegistroLotes,
    totalLotes: 2, lotesLiberados: 0, lotesRechazados: 0,
  },
  {
    id: "rec-006", numeroRecepcion: "REC-2026-0043",
    ordenCompraNumero: "OC-2026-0094",
    proveedorNombre: "Alimentos Deli Ltda.", proveedorId: "prov-006",
    fechaRecepcion: "2026-02-20", horaLlegadaVehiculo: "11:00:00",
    placaVehiculo: "GHI-555",
    estado: EstadoRecepcion.InspeccionVehiculo,
    totalLotes: 0, lotesLiberados: 0, lotesRechazados: 0,
  },
];

export const MOCK_DETALLE: RecepcionDetalle = {
  id: "rec-001",
  numeroRecepcion: "REC-2026-0048",
  ordenCompraNumero: "OC-2026-0112",
  numeroOC: "OC-2026-0112",
  proveedorNombre: "AviCol S.A.",
  proveedorId: "prov-001",
  fechaRecepcion: "2026-02-24",
  horaLlegadaVehiculo: "07:30:00",
  placaVehiculo: "OPQ-451",
  nombreTransportista: "Luis García",
  estado: EstadoRecepcion.PendienteCalidad,
  totalLotes: 3,
  lotesLiberados: 0,
  lotesRechazados: 0,
  observacionesGenerales: "Vehículo llegó puntual. Sin novedades en el ingreso.",

  inspeccionVehiculo: {
    id: "insp-001",
    temperaturaInicial: 4.2,
    temperaturaDentroRango: true,
    integridadEmpaque: true,
    limpiezaVehiculo: true,
    presenciaOloresExtranos: false,
    plagasVisible: false,
    documentosTransporteOk: true,
    resultado: 0,
    observaciones: "Compartimento limpio y con temperatura adecuada.",
    registradoPorNombre: "Luis García",
    fechaRegistro: "2026-02-24T07:35:00Z",
  },

  // ← Ahora usa LoteResumen (campos del backend DTO)
  lotes: [
    {
      id: "lote-001",
      codigoLoteInterno: "LI-2026-0301",
      numeroLoteProveedor: "AVI-20260224-A",
      itemCodigo: "AVE-001",
      itemNombre: "Pollo entero fresco",
      fechaVencimiento: "2026-03-01",
      diasVidaUtilRestantes: 5,
      estaVencido: false,
      cantidadRecibida: 120,
      cantidadRechazada: 0,
      estado: "PendienteCalidad",
      ubicacionDestino: 0,
    },
    {
      id: "lote-002",
      codigoLoteInterno: "LI-2026-0302",
      numeroLoteProveedor: "AVI-20260224-B",
      itemCodigo: "AVE-002",
      itemNombre: "Muslo de pollo",
      fechaVencimiento: "2026-03-02",
      diasVidaUtilRestantes: 6,
      estaVencido: false,
      cantidadRecibida: 80,
      cantidadRechazada: 0,
      estado: "PendienteCalidad",
      ubicacionDestino: 0,
    },
    {
      id: "lote-003",
      codigoLoteInterno: "LI-2026-0303",
      numeroLoteProveedor: "AVI-20260224-C",
      itemCodigo: "AVE-003",
      itemNombre: "Pechuga de pollo sin hueso",
      fechaVencimiento: "2026-03-03",
      diasVidaUtilRestantes: 7,
      estaVencido: false,
      cantidadRecibida: 50,
      cantidadRechazada: 0,
      estado: "PendienteCalidad",
      ubicacionDestino: 1,
    },
  ],

  documentos: [
    {
      id: "doc-rec-001",
      tipoDocumento: 3,
      nombreArchivo: "INVIMA_AviCol_2026.pdf",
      adjuntoUrl: "#",
      fechaCarga: "2026-02-24T07:38:00Z",
      cargadoPorNombre: "dev-user",
      esValido: true,
    },
    {
      id: "doc-rec-002",
      tipoDocumento: 4,
      nombreArchivo: "BitacoraTemp_OPQ451_20260224.pdf",
      adjuntoUrl: "#",
      fechaCarga: "2026-02-24T07:39:00Z",
      cargadoPorNombre: "dev-user",
    },
  ],

  registrosTemperatura: [
    {
      id: "temp-001",
      temperatura: 3.8,
      unidadMedida: "°C",
      fechaHora: "2026-02-24T07:31:00Z",
      origen: 0,
      estaFueraDeRango: false,
      registradoPorNombre: "dev-user",
    },
    {
      id: "temp-002",
      temperatura: 5.9,
      unidadMedida: "°C",
      fechaHora: "2026-02-24T07:33:00Z",
      origen: 0,
      estaFueraDeRango: true,
      observacion: "Temperatura ligeramente elevada — lote enviado a cuarentena.",
      registradoPorNombre: "dev-user",
    },
  ],
};