import type { LotePendiente } from "../../Services/lotes.service";

export const MOCK_LOTES_PENDIENTES: LotePendiente[] = [
  {
    id: "lote-001", numeroLoteInterno: "L-2026-0048-01", numeroLoteProveedor: "AVL-20260201",
    itemId: "item-001", itemNombre: "Pechuga de pollo", itemCodigo: "CAR-001",
    categoriaNombre: "Cárnicos", requiereCadenaFrio: true,
    temperaturaMinima: 0, temperaturaMaxima: 4,
    recepcionId: "rec-001", numeroRecepcion: "REC-2026-0048",
    proveedorNombre: "AviCol S.A.",
    fechaRecepcion: "2026-02-24", fechaFabricacion: "2026-02-01",
    fechaVencimiento: "2026-03-01", diasParaVencer: 5,
    cantidadRecibida: 498, unidadMedida: "Kg",
    temperaturaMedida: 3.5, temperaturaDentroRango: true,
    estadoSensorial: 0, estadoRotulado: 0, ubicacionDestino: 0,
    estado: "PendienteCalidad",
    cantidadEsperada: 0,
    tieneDocumentosFaltantes: false,
    documentosFaltantes: []
  },
  {
    id: "lote-002", numeroLoteInterno: "L-2026-0048-02", numeroLoteProveedor: "AVL-20260202",
    itemId: "item-002", itemNombre: "Muslo de pollo", itemCodigo: "CAR-002",
    categoriaNombre: "Cárnicos", requiereCadenaFrio: true,
    temperaturaMinima: 0, temperaturaMaxima: 4,
    recepcionId: "rec-001", numeroRecepcion: "REC-2026-0048",
    proveedorNombre: "AviCol S.A.",
    fechaRecepcion: "2026-02-24", fechaFabricacion: "2026-02-01",
    fechaVencimiento: "2026-03-03", diasParaVencer: 7,
    cantidadRecibida: 300, unidadMedida: "Kg",
    temperaturaMedida: 3.8, temperaturaDentroRango: true,
    estadoSensorial: 0, estadoRotulado: 0, ubicacionDestino: 0,
    estado: "PendienteCalidad",
    cantidadEsperada: 0,
    tieneDocumentosFaltantes: false,
    documentosFaltantes: []
  },
  {
    id: "lote-003", numeroLoteInterno: "L-2026-0044-01",
    itemId: "item-006", itemNombre: "Azúcar refinada", itemCodigo: "SEC-001",
    categoriaNombre: "Secos", requiereCadenaFrio: false,
    recepcionId: "rec-005", numeroRecepcion: "REC-2026-0044",
    proveedorNombre: "Riopaila Castilla",
    fechaRecepcion: "2026-02-21",
    fechaVencimiento: "2028-02-01", diasParaVencer: 342,
    cantidadRecibida: 2000, unidadMedida: "Kg",
    estadoSensorial: 0, estadoRotulado: 0, ubicacionDestino: 0,
    estado: "PendienteCalidad",
    observacionesRecepcion: "Sacos en buen estado. Sin humedad visible.",
    cantidadEsperada: 0,
    tieneDocumentosFaltantes: false,
    documentosFaltantes: []
  },
  {
    id: "lote-004", numeroLoteInterno: "L-2026-0044-02",
    itemId: "item-007", itemNombre: "Azúcar morena", itemCodigo: "SEC-002",
    categoriaNombre: "Secos", requiereCadenaFrio: false,
    recepcionId: "rec-005", numeroRecepcion: "REC-2026-0044",
    proveedorNombre: "Riopaila Castilla",
    fechaRecepcion: "2026-02-21",
    fechaVencimiento: "2028-01-15", diasParaVencer: 325,
    cantidadRecibida: 498, unidadMedida: "Kg",
    estadoSensorial: 1, estadoRotulado: 0, ubicacionDestino: 1,
    estado: "PendienteCalidad",
    observacionesRecepcion: "Lote enviado a cuarentena preventiva — 2 sacos con humedad superficial.",
    cantidadEsperada: 0,
    tieneDocumentosFaltantes: false,
    documentosFaltantes: []
  },
  {
    id: "lote-005", numeroLoteInterno: "L-2026-0047-01",
    itemId: "item-003", itemNombre: "Leche entera UHT", itemCodigo: "LAC-001",
    categoriaNombre: "Lácteos", requiereCadenaFrio: true,
    temperaturaMinima: 2, temperaturaMaxima: 8,
    recepcionId: "rec-002", numeroRecepcion: "REC-2026-0047",
    proveedorNombre: "Lácteos del Valle",
    fechaRecepcion: "2026-02-23",
    fechaVencimiento: "2026-06-15", diasParaVencer: 110,
    cantidadRecibida: 1000, unidadMedida: "L",
    temperaturaMedida: 6.2, temperaturaDentroRango: true,
    estadoSensorial: 0, estadoRotulado: 0, ubicacionDestino: 0,
    estado: "PendienteCalidad",
    cantidadEsperada: 0,
    tieneDocumentosFaltantes: false,
    documentosFaltantes: []
  },
];