// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaRecepcionMP.Infraestructure.Persistence;

#nullable disable

namespace SistemaRecepcionMP.Infraestructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.AccionCorrectiva", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DescripcionAccion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EvidenciaUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly?>("FechaCierre")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaCompromiso")
                        .HasColumnType("date");

                    b.Property<Guid>("NoConformidadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ResponsableId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NoConformidadId");

                    b.HasIndex("ResponsableId");

                    b.ToTable("AccionesCorrectivas", (string)null);
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.BitacoraAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EntidadAfectada")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpOrigen")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("RegistroId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ValorAnterior")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValorNuevo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FechaHora");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("EntidadAfectada", "RegistroId");

                    b.ToTable("BitacoraAuditoria", (string)null);
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.CategoriaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequiereCadenaFrio")
                        .HasColumnType("bit");

                    b.Property<bool>("RequierePresenciaCalidad")
                        .HasColumnType("bit");

                    b.Property<int>("VidaUtilMinimaDias")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CategoriasItem");
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.CausalNoConformidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoAccionSugerida")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CausalesNoConformidad");
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.ChecklistBPM", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId", "Estado")
                        .IsUnique()
                        .HasFilter("[Estado] = 1");

                    b.ToTable("ChecklistsBPM", (string)null);
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.ComentarioNoConformidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AutorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("NoConformidadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("NoConformidadId");

                    b.ToTable("ComentariosNoConformidad", (string)null);
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.ContactoProveedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cargo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ProveedorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ProveedorId");

                    b.ToTable("ContactosProveedor", (string)null);
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.Cuarentena", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccionesRealizadas")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Decision")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("FechaCuarentena")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaLiberacion")
                        .HasColumnType("date");

                    b.Property<Guid>("LoteRecibidoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("SeguidoPor")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LoteRecibidoId")
                        .IsUnique();

                    b.HasIndex("SeguidoPor");

                    b.ToTable("Cuarentenas", (string)null);
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.DetalleOrdenCompra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CantidadRechazada")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(12,3)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("CantidadRecibida")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(12,3)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("CantidadSolicitada")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(12,3)");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrdenCompraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(16,2)");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("OrdenCompraId");

                    b.ToTable("DetallesOrdenCompra", (string)null);
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.DocumentoRecepcion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdjuntoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("CargadoPor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("EsValido")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LoteRecibidoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ObservacionValidacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RecepcionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("TipoDocumentoExigidoCategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CargadoPor");

                    b.HasIndex("LoteRecibidoId");

                    b.HasIndex("RecepcionId");

                    b.HasIndex("TipoDocumentoExigidoCategoriaId");

                    b.ToTable("DocumentosRecepcion", (string)null);
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.DocumentoSanitarioProveedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdjuntoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly>("FechaExpedicion")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaVencimiento")
                        .HasColumnType("date");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ProveedorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TipoDocumento")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProveedorId");

                    b.ToTable("DocumentosSanitariosProveedor", (string)null);
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.Factura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdjuntoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("FechaFactura")
                        .HasColumnType("date");

                    b.Property<string>("NotaCreditoNumero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("NotaCreditoValor")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("RecepcionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RecepcionId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("RecepcionId")
                        .IsUnique();

                    b.HasIndex("RecepcionId1");

                    b.ToTable("Facturas", (string)null);
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.InspeccionVehiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DocumentosTransporteOk")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IntegridadEmpaque")
                        .HasColumnType("bit");

                    b.Property<bool>("LimpiezaVehiculo")
                        .HasColumnType("bit");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("PlagasVisible")
                        .HasColumnType("bit");

                    b.Property<bool>("PresenciaOloresExtranos")
                        .HasColumnType("bit");

                    b.Property<Guid>("RecepcionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RegistradoPor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TemperaturaDentroRango")
                        .HasColumnType("bit");

                    b.Property<decimal?>("TemperaturaInicial")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("RecepcionId")
                        .IsUnique();

                    b.HasIndex("RegistradoPor");

                    b.ToTable("InspeccionesVehiculo", (string)null);
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodigoInterno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequiereLoteProveedor")
                        .HasColumnType("bit");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VidaUtilDias")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.ItemChecklist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChecklistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Criterio")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("EsCritico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<int>("TipoCriterio")
                        .HasColumnType("int");

                    b.Property<string>("Unidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ValorMaximo")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ValorMinimo")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistId", "Orden")
                        .IsUnique();

                    b.ToTable("ItemsChecklist", (string)null);
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.LiberacionLote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaLiberacion")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LiberadoPor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LoteRecibidoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("LiberadoPor");

                    b.HasIndex("LoteRecibidoId")
                        .IsUnique();

                    b.ToTable("LiberacionesLote", (string)null);
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.LoteRecibido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CantidadRechazada")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(12,3)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("CantidadRecibida")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(12,3)");

                    b.Property<string>("CodigoLoteInterno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodigoQr")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("DetalleOrdenCompraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EstadoRotulado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EstadoSensorial")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("FechaFabricacion")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("FechaVencimiento")
                        .HasColumnType("date");

                    b.Property<string>("NumeroLoteProveedor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ObservacionesCalidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RecepcionItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RegistradoPor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("TemperaturaMedida")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("UbicacionDestino")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoLoteInterno")
                        .IsUnique();

                    b.HasIndex("DetalleOrdenCompraId");

                    b.HasIndex("RecepcionItemId");

                    b.HasIndex("RegistradoPor");

                    b.ToTable("LotesRecibidos", null, t =>
                        {
                            t.Property("FechaVencimiento")
                                .HasColumnName("LoteRecibido_FechaVencimiento");
                        });
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.NoConformidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AsignadoA")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("CantidadAfectada")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("CausaRaiz")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("CausalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreadoPor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("FechaLimite")
                        .HasColumnType("date");

                    b.Property<Guid>("LoteRecibidoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ObservacionesCierre")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Prioridad")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UsuarioCreadorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CausalId");

                    b.HasIndex("LoteRecibidoId");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.HasIndex("UsuarioCreadorId");

                    b.ToTable("NoConformidades", (string)null);
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.OrdenCompra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreadoPor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FechaEmision")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaEntregaEsperada")
                        .HasColumnType("date");

                    b.Property<string>("NumeroOC")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ProveedorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreadoPor");

                    b.HasIndex("NumeroOC")
                        .IsUnique();

                    b.HasIndex("ProveedorId");

                    b.ToTable("OrdenesCompra", (string)null);
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.Proveedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("EmailContacto")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Nit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Proveedores", (string)null);
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.Recepcion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreadoPorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FechaFinalizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("FechaRecepcion")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("HoraLlegadaVehiculo")
                        .HasColumnType("time");

                    b.Property<string>("NombreTransportista")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NumeroRecepcion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ObservacionesGenerales")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("OrdenCompraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OrdenCompraId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PlacaVehiculo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid>("ProveedorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Resultado")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreadoPorId");

                    b.HasIndex("NumeroRecepcion")
                        .IsUnique();

                    b.HasIndex("OrdenCompraId");

                    b.HasIndex("OrdenCompraId1");

                    b.HasIndex("ProveedorId");

                    b.ToTable("Recepciones", (string)null);
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.RecepcionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CantidadEsperada")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("CantidadRechazada")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("CantidadRecibida")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("DetalleOrdenCompraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RecepcionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DetalleOrdenCompraId");

                    b.HasIndex("ItemId");

                    b.HasIndex("RecepcionId");

                    b.ToTable("RecepcionItem");
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.ResultadoChecklist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChecklistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ItemChecklistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ItemChecklistId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LoteRecibidoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Observacion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("RegistradoPor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistId");

                    b.HasIndex("ItemChecklistId");

                    b.HasIndex("ItemChecklistId1");

                    b.HasIndex("RegistradoPor");

                    b.HasIndex("LoteRecibidoId", "ItemChecklistId")
                        .IsUnique();

                    b.ToTable("ResultadosChecklist", (string)null);
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.TemperaturaRegistro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DispositivoId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EstaFueraDeRango")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LoteRecibidoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Observacion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("RecepcionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RegistradoPor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Temperatura")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("Id");

                    b.HasIndex("LoteRecibidoId");

                    b.HasIndex("RecepcionId");

                    b.HasIndex("RegistradoPor");

                    b.ToTable("RegistrosTemperatura", (string)null);
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.TipoDocumentoExigidoCategoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsObligatorio")
                        .HasColumnType("bit");

                    b.Property<int>("TipoDocumento")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("TiposDocumentoExigidoCategoria");
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntraId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Perfil")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.AccionCorrectiva", b =>
                {
                    b.HasOne("SistemaRecepcionMP.Domain.Entities.NoConformidad", "NoConformidad")
                        .WithMany("AccionesCorrectivas")
                        .HasForeignKey("NoConformidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaRecepcionMP.Domain.Entities.Usuario", "UsuarioResponsable")
                        .WithMany()
                        .HasForeignKey("ResponsableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NoConformidad");

                    b.Navigation("UsuarioResponsable");
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.BitacoraAuditoria", b =>
                {
                    b.HasOne("SistemaRecepcionMP.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.CategoriaItem", b =>
                {
                    b.OwnsOne("SistemaRecepcionMP.Domain.ValueObjects.RangoTemperatura", "RangoTemperatura", b1 =>
                        {
                            b1.Property<Guid>("CategoriaItemId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Maxima")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)");

                            b1.Property<decimal>("Minima")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)");

                            b1.HasKey("CategoriaItemId");

                            b1.ToTable("CategoriasItem");

                            b1.WithOwner()
                                .HasForeignKey("CategoriaItemId");
                        });

                    b.Navigation("RangoTemperatura");
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.ChecklistBPM", b =>
                {
                    b.HasOne("SistemaRecepcionMP.Domain.Entities.CategoriaItem", "Categoria")
                        .WithMany("Checklists")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.ComentarioNoConformidad", b =>
                {
                    b.HasOne("SistemaRecepcionMP.Domain.Entities.Usuario", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaRecepcionMP.Domain.Entities.NoConformidad", "NoConformidad")
                        .WithMany("Comentarios")
                        .HasForeignKey("NoConformidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("NoConformidad");
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.ContactoProveedor", b =>
                {
                    b.HasOne("SistemaRecepcionMP.Domain.Entities.Proveedor", "Proveedor")
                        .WithMany("Contactos")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.Cuarentena", b =>
                {
                    b.HasOne("SistemaRecepcionMP.Domain.Entities.LoteRecibido", "LoteRecibido")
                        .WithOne("Cuarentena")
                        .HasForeignKey("SistemaRecepcionMP.Domain.Entities.Cuarentena", "LoteRecibidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaRecepcionMP.Domain.Entities.Usuario", "UsuarioCalidad")
                        .WithMany()
                        .HasForeignKey("SeguidoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LoteRecibido");

                    b.Navigation("UsuarioCalidad");
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.DetalleOrdenCompra", b =>
                {
                    b.HasOne("SistemaRecepcionMP.Domain.Entities.Item", "Item")
                        .WithMany("DetallesOrdenCompra")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaRecepcionMP.Domain.Entities.OrdenCompra", "OrdenCompra")
                        .WithMany("Detalles")
                        .HasForeignKey("OrdenCompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("OrdenCompra");
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.DocumentoRecepcion", b =>
                {
                    b.HasOne("SistemaRecepcionMP.Domain.Entities.Usuario", "UsuarioCargador")
                        .WithMany()
                        .HasForeignKey("CargadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaRecepcionMP.Domain.Entities.LoteRecibido", "LoteRecibido")
                        .WithMany("Documentos")
                        .HasForeignKey("LoteRecibidoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SistemaRecepcionMP.Domain.Entities.Recepcion", "Recepcion")
                        .WithMany("Documentos")
                        .HasForeignKey("RecepcionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SistemaRecepcionMP.Domain.Entities.TipoDocumentoExigidoCategoria", "TipoDocumentoExigidoCategoria")
                        .WithMany()
                        .HasForeignKey("TipoDocumentoExigidoCategoriaId");

                    b.Navigation("LoteRecibido");

                    b.Navigation("Recepcion");

                    b.Navigation("TipoDocumentoExigidoCategoria");

                    b.Navigation("UsuarioCargador");
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.DocumentoSanitarioProveedor", b =>
                {
                    b.HasOne("SistemaRecepcionMP.Domain.Entities.Proveedor", "Proveedor")
                        .WithMany("DocumentosSanitarios")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.Factura", b =>
                {
                    b.HasOne("SistemaRecepcionMP.Domain.Entities.Recepcion", "Recepcion")
                        .WithOne("Factura")
                        .HasForeignKey("SistemaRecepcionMP.Domain.Entities.Factura", "RecepcionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaRecepcionMP.Domain.Entities.Recepcion", null)
                        .WithMany("Facturas")
                        .HasForeignKey("RecepcionId1");

                    b.Navigation("Recepcion");
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.InspeccionVehiculo", b =>
                {
                    b.HasOne("SistemaRecepcionMP.Domain.Entities.Recepcion", "Recepcion")
                        .WithOne("InspeccionVehiculo")
                        .HasForeignKey("SistemaRecepcionMP.Domain.Entities.InspeccionVehiculo", "RecepcionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaRecepcionMP.Domain.Entities.Usuario", "UsuarioRegistrador")
                        .WithMany()
                        .HasForeignKey("RegistradoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recepcion");

                    b.Navigation("UsuarioRegistrador");
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.Item", b =>
                {
                    b.HasOne("SistemaRecepcionMP.Domain.Entities.CategoriaItem", "Categoria")
                        .WithMany("Items")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("SistemaRecepcionMP.Domain.ValueObjects.RangoTemperatura", "RangoTemperatura", b1 =>
                        {
                            b1.Property<Guid>("ItemId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Maxima")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)");

                            b1.Property<decimal>("Minima")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)");

                            b1.HasKey("ItemId");

                            b1.ToTable("Items");

                            b1.WithOwner()
                                .HasForeignKey("ItemId");
                        });

                    b.Navigation("Categoria");

                    b.Navigation("RangoTemperatura");
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.ItemChecklist", b =>
                {
                    b.HasOne("SistemaRecepcionMP.Domain.Entities.ChecklistBPM", "Checklist")
                        .WithMany("Items")
                        .HasForeignKey("ChecklistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Checklist");
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.LiberacionLote", b =>
                {
                    b.HasOne("SistemaRecepcionMP.Domain.Entities.Usuario", "UsuarioCalidad")
                        .WithMany()
                        .HasForeignKey("LiberadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaRecepcionMP.Domain.Entities.LoteRecibido", "LoteRecibido")
                        .WithOne("Liberacion")
                        .HasForeignKey("SistemaRecepcionMP.Domain.Entities.LiberacionLote", "LoteRecibidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoteRecibido");

                    b.Navigation("UsuarioCalidad");
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.LoteRecibido", b =>
                {
                    b.HasOne("SistemaRecepcionMP.Domain.Entities.DetalleOrdenCompra", "DetalleOrdenCompra")
                        .WithMany()
                        .HasForeignKey("DetalleOrdenCompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaRecepcionMP.Domain.Entities.RecepcionItem", "RecepcionItem")
                        .WithMany("Lotes")
                        .HasForeignKey("RecepcionItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaRecepcionMP.Domain.Entities.Usuario", "UsuarioRegistrador")
                        .WithMany()
                        .HasForeignKey("RegistradoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("SistemaRecepcionMP.Domain.ValueObjects.VidaUtil", "VidaUtil", b1 =>
                        {
                            b1.Property<Guid>("LoteRecibidoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly>("FechaVencimiento")
                                .HasColumnType("date")
                                .HasColumnName("FechaVencimiento");

                            b1.HasKey("LoteRecibidoId");

                            b1.ToTable("LotesRecibidos");

                            b1.WithOwner()
                                .HasForeignKey("LoteRecibidoId");
                        });

                    b.Navigation("DetalleOrdenCompra");

                    b.Navigation("RecepcionItem");

                    b.Navigation("UsuarioRegistrador");

                    b.Navigation("VidaUtil");
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.NoConformidad", b =>
                {
                    b.HasOne("SistemaRecepcionMP.Domain.Entities.CausalNoConformidad", "Causal")
                        .WithMany("NoConformidades")
                        .HasForeignKey("CausalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaRecepcionMP.Domain.Entities.LoteRecibido", "LoteRecibido")
                        .WithMany("NoConformidades")
                        .HasForeignKey("LoteRecibidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaRecepcionMP.Domain.Entities.Usuario", "UsuarioCreador")
                        .WithMany()
                        .HasForeignKey("UsuarioCreadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Causal");

                    b.Navigation("LoteRecibido");

                    b.Navigation("UsuarioCreador");
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.OrdenCompra", b =>
                {
                    b.HasOne("SistemaRecepcionMP.Domain.Entities.Usuario", "UsuarioCreador")
                        .WithMany()
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaRecepcionMP.Domain.Entities.Proveedor", "Proveedor")
                        .WithMany("OrdenesCompra")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proveedor");

                    b.Navigation("UsuarioCreador");
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.Recepcion", b =>
                {
                    b.HasOne("SistemaRecepcionMP.Domain.Entities.Usuario", "CreadoPor")
                        .WithMany()
                        .HasForeignKey("CreadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaRecepcionMP.Domain.Entities.OrdenCompra", "OrdenCompra")
                        .WithMany()
                        .HasForeignKey("OrdenCompraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaRecepcionMP.Domain.Entities.OrdenCompra", null)
                        .WithMany("Recepciones")
                        .HasForeignKey("OrdenCompraId1");

                    b.HasOne("SistemaRecepcionMP.Domain.Entities.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreadoPor");

                    b.Navigation("OrdenCompra");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.RecepcionItem", b =>
                {
                    b.HasOne("SistemaRecepcionMP.Domain.Entities.DetalleOrdenCompra", "DetalleOrdenCompra")
                        .WithMany()
                        .HasForeignKey("DetalleOrdenCompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaRecepcionMP.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaRecepcionMP.Domain.Entities.Recepcion", "Recepcion")
                        .WithMany("Items")
                        .HasForeignKey("RecepcionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DetalleOrdenCompra");

                    b.Navigation("Item");

                    b.Navigation("Recepcion");
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.ResultadoChecklist", b =>
                {
                    b.HasOne("SistemaRecepcionMP.Domain.Entities.ChecklistBPM", "Checklist")
                        .WithMany("Resultados")
                        .HasForeignKey("ChecklistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaRecepcionMP.Domain.Entities.ItemChecklist", "ItemChecklist")
                        .WithMany()
                        .HasForeignKey("ItemChecklistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaRecepcionMP.Domain.Entities.ItemChecklist", null)
                        .WithMany("Resultados")
                        .HasForeignKey("ItemChecklistId1");

                    b.HasOne("SistemaRecepcionMP.Domain.Entities.LoteRecibido", "LoteRecibido")
                        .WithMany("ResultadosChecklist")
                        .HasForeignKey("LoteRecibidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaRecepcionMP.Domain.Entities.Usuario", "UsuarioRegistrador")
                        .WithMany()
                        .HasForeignKey("RegistradoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Checklist");

                    b.Navigation("ItemChecklist");

                    b.Navigation("LoteRecibido");

                    b.Navigation("UsuarioRegistrador");
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.TemperaturaRegistro", b =>
                {
                    b.HasOne("SistemaRecepcionMP.Domain.Entities.LoteRecibido", "LoteRecibido")
                        .WithMany("RegistrosTemperatura")
                        .HasForeignKey("LoteRecibidoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SistemaRecepcionMP.Domain.Entities.Recepcion", "Recepcion")
                        .WithMany("RegistrosTemperatura")
                        .HasForeignKey("RecepcionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SistemaRecepcionMP.Domain.Entities.Usuario", "UsuarioRegistrador")
                        .WithMany()
                        .HasForeignKey("RegistradoPor")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LoteRecibido");

                    b.Navigation("Recepcion");

                    b.Navigation("UsuarioRegistrador");
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.TipoDocumentoExigidoCategoria", b =>
                {
                    b.HasOne("SistemaRecepcionMP.Domain.Entities.CategoriaItem", "Categoria")
                        .WithMany("DocumentosExigidos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.CategoriaItem", b =>
                {
                    b.Navigation("Checklists");

                    b.Navigation("DocumentosExigidos");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.CausalNoConformidad", b =>
                {
                    b.Navigation("NoConformidades");
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.ChecklistBPM", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Resultados");
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.Item", b =>
                {
                    b.Navigation("DetallesOrdenCompra");
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.ItemChecklist", b =>
                {
                    b.Navigation("Resultados");
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.LoteRecibido", b =>
                {
                    b.Navigation("Cuarentena");

                    b.Navigation("Documentos");

                    b.Navigation("Liberacion");

                    b.Navigation("NoConformidades");

                    b.Navigation("RegistrosTemperatura");

                    b.Navigation("ResultadosChecklist");
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.NoConformidad", b =>
                {
                    b.Navigation("AccionesCorrectivas");

                    b.Navigation("Comentarios");
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.OrdenCompra", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Recepciones");
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.Proveedor", b =>
                {
                    b.Navigation("Contactos");

                    b.Navigation("DocumentosSanitarios");

                    b.Navigation("OrdenesCompra");
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.Recepcion", b =>
                {
                    b.Navigation("Documentos");

                    b.Navigation("Factura");

                    b.Navigation("Facturas");

                    b.Navigation("InspeccionVehiculo");

                    b.Navigation("Items");

                    b.Navigation("RegistrosTemperatura");
                });

            modelBuilder.Entity("SistemaRecepcionMP.Domain.Entities.RecepcionItem", b =>
                {
                    b.Navigation("Lotes");
                });
#pragma warning restore 612, 618
        }
    }
}
